name: release

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/megatron-energon
    permissions:
      id-token: write  # This permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python -m build -w
          python -m build -s
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
