system:
  tensor_model_parallel_size: 4
  pipeline_model_parallel_size: 2
  disable_bias_linear: True
  use_flash_attn: True
  sequence_parallel: True
  use_distributed_optimizer: True
  precision:
    bf16: True
    attention_softmax_in_fp32: true
    accumulate_allreduce_grads_in_fp32: true
  logging:
    log_interval: 5
    tensorboard_log_interval: 5
    wandb_project: "train-llama3-8B" 
    wandb_exp_name: "train-test-8B" 
  checkpoint:
    save_interval: 10
    # finetune: True
    ckpt_format: "torch"

  hetero:
    enable_hetero: True
    hetero_use_cpu_communication: False
    # mesh format [tp1,cp1,ep1,dp1,pp1,(tp2,cp2...)]

    # 1 mesh, diff pp
    # hetero_pipeline_layer_split: [4, 2, 2, 4]
    # hetero_process_meshes: [2, 1, 1, 1, 4]
    # hetero_device_types: ["A800"]

    # 2 mesh, diff pp
    # hetero_pipeline_layer_split: [4, 2, 2, 4]
    # hetero_process_meshes: [2, 1, 1, 1, 3, 2, 1, 1, 1, 1]
    # hetero_device_types: ["A800", "A800"]


    # 2 mesh, diff pp and tp
    # hetero_pipeline_layer_split: [6, 2, 4]
    # hetero_process_meshes: [2, 1, 1, 1, 2, 4, 1, 1, 1, 1]
    # hetero_device_types: ["A800", "A800"]

    # 3 mesh
    hetero_pipeline_layer_split: [16,16]
    hetero_process_meshes: [2, 1, 1, 4, 1, 2, 1, 1, 4, 1]

    # hetero_pipeline_layer_split: [9,9,7,7]
    # hetero_process_meshes: [4, 1, 1, 1, 2, 4, 1, 1, 1, 2]
    hetero_device_types: ["A800", "A100"]
    
    standalone_embedding_stage: False
    hetero_current_device_type: "A800"

  # recompute:
  #   recompute_granularity: "full" 
  #   recompute_method: "uniform"
  #   recompute_num_layers: 1

  #   ## pp 3 stages
  #   recompute_granularity_per_stage_micro_batch:
  #     - [1, 15, 0, 1, 0]
  #     - [1, 15, 1, 1, 1]
  #     - [1, 15, 1, 1, 1]
  #   recompute_method_per_stage_micro_batch:
  #     - [1, 15, 0, 1, 0]
  #     - [1, 15, 0, 1, 0]
  #     - [1, 15, 1, 1, 1]
  #   recompute_num_layers_per_stage_micro_batch:
  #     - [1, 15, 2, 1, 2]
  #     - [1, 15, 1, 1, 1]
  #     - [1, 15, 2, 1, 2]
  

model:
  use_mcore_models: True
  transformer_impl: transformer_engine
  num_layers: 32    
  hidden_size: 4096 
  ffn_hidden_size: 14336
  num_attention_heads: 32 
  seq_length: 4096  
  group_query_attention: True
  num_query_groups: 8
  max_position_embeddings: 8192
  norm_epsilon: 1e-5
  use_rotary_position_embeddings: True
  no_position_embedding: True
  swiglu: True
  normalization: RMSNorm
  rotary_interleaved_patch: False
  position_embedding_type: rope
  rotary_base: 500000
  untie_embeddings_and_output_weights: True
  init_method_std: 0.02
  attention_dropout: 0.0
  hidden_dropout: 0.0
  clip_grad: 1.0
  train_samples: 320
  eval_iters: 1000
  eval_interval: 10000
  micro_batch_size: 1
  global_batch_size: 16 

  optimizer:
    weight_decay: 1e-2
    adam_beta1: 0.9
    adam_beta2: 0.95
    lr_scheduler:
      lr: 1.0e-5
      min_lr: 1.0e-6
      lr_warmup_fraction: .1
      lr_decay_style: cosine 

data:
  data_path: /share/project/lizhiyu/FlagScale/build/data/pile_wikipedia_demo
  split: 1 
  tokenizer:
    tokenizer_type: Llama3TokenizerFS
    tokenizer_path: /share/project/liangdong/Profiler/FlagScale/Llama-3-70B/
    vocab_size: 128256
    make_vocab_size_divisible_by: 64


    # NCCL_IB_HCA=mlx5_2,mlx5_8