data:
  data_path: /share/project/PUBLIC/data/llama3-70b/llama3_dataset/dedup-md5-pile-pile-cc_text_document
  split: 1
  tokenizer:
    tokenizer_path: /share/project/PUBLIC/data/llama3-70b/llama3_tokenizer
    tokenizer_type: Llama3TokenizerFS
    vocab_size: 128256
model:
  add_qkv_bias: false
  attention_dropout: 0.0
  clip_grad: 1.0
  ffn_hidden_size: 28672
  global_batch_size: 1024
  group_query_attention: true
  hidden_dropout: 0.0
  hidden_size: 8192
  init_method_std: 0.02
  max_position_embeddings: 8192
  micro_batch_size: 1
  no_position_embedding: true
  norm_epsilon: 1e-5
  norm_init_weight: 0.02
  normalization: RMSNorm
  num_attention_heads: 64
  num_layers: 80
  num_query_groups: 8
  optimizer:
    adam_beta1: 0.9
    adam_beta2: 0.95
    end_weight_decay: 5e-7
    lr_scheduler:
      lr: 5e-6
      lr_decay_style: cosine
      lr_warmup_samples: 51200
      min_lr: 0
    start_weight_decay: 0
    weight_decay_incr_style: cosine
  reset_attention_mask: true
  reset_position_ids: true
  rotary_base: 500000
  seed: 42
  seq_length: 8192
  swiglu: true
  train_samples: 512000
  transformer_impl: transformer_engine
  untie_embeddings_and_output_weights: true
  use_mcore_models: true
  use_rotary_position_embeddings: true
system:
  checkpoint:
    ckpt_format: torch
    finetune: true
    load: /share/project/PUBLIC/data/llama3-70b/llama3_ckpt
    save_interval: 100
  disable_bias_linear: true
  logging:
    log_interval: 1
    tensorboard_log_interval: 1
    wandb_exp_name: train-llama3-70B
    wandb_project: train-llama3-70B
  make_vocab_size_divisible_by: 64
  pipeline_model_parallel_size: 4
  precision:
    accumulate_allreduce_grads_in_fp32: true
    attention_softmax_in_fp32: true
    bf16: true
  sequence_parallel: true
  tensor_model_parallel_size: 8
  transformer_impl: transformer_engine
  use_distributed_optimizer: true
  use_flash_attn: true
  use_mcore_models: true
