defaults:
  - _self_
  - train: 3_3b

experiment:
  exp_name: Robotics-3.3B
  seed: 42
  save_steps: 10000
  load: null
  exp_dir: outputs/${experiment.exp_name}
  ckpt_format: torch
  task:
    type: train
    backend: robotics
    entrypoint: flagscale/train/train_robotics_ddp.py
  runner:
    per_node_task: false
    no_shared_fs: false
    rdzv_backend: static
    hostfile: null
  cmds:
    before_start: echo "Starting Robotics Training"
  envs:
    LOGLEVEL: "INFO"
    CUDA_VISIBLE_DEVICES: "1"
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    # Set python paths for: robotics, lerobot, openpi-client, FlagScale, Megatron-LM
    PYTHONPATH: python/paths
    # Set lerobot data path
    HF_LEROBOT_HOME: lerobot/data/path
    WANDB_MODE: offline


action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
