defaults:
  - _self_
  - train: 3_3b

experiment:
  exp_name: Robotics-3.3B
  seed: 42
  save_steps: 10000
  load: null
  exp_dir: outputs/${experiment.exp_name}
  ckpt_format: torch
  task:
    type: train
    backend: robotics
    # entrypoint: flagscale/train/train_robotics_fsdp.py
    entrypoint: flagscale/train/train_robotics_ddp_v3.py
  runner:
    per_node_task: false
    no_shared_fs: false
    rdzv_backend: static
    hostfile: null
  cmds:
    before_start: echo "Starting Robotics Training"
  envs:
    LOGLEVEL: "INFO"
    CUDA_VISIBLE_DEVICES: "1"
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    # /share/project/fengyupu/conda_env/openpi/lib/python3.11/site-packages
    # PYTHONPATH: /share/project/hcr/repos/flag-scale:/share/project/hcr/repos/flag-scale/third_party/robotics/packages/lerobot:/share/project/lyx/openpi/packages/openpi-client/src
    PYTHONPATH: /share/project/hcr/repos/flag-scale:/share/project/section/robotics_hcr/src:/share/project/section/robotics/packages/lerobot:/share/project/section/robotics/packages/openpi-client/src:/share/project/hcr/repos/flag-scale/third_party/Megatron-LM
    HF_LEROBOT_HOME: /share/project/lyx/openpi/data
    WANDB_MODE: offline


action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
