system:
  tensor_model_parallel_size: 4
  pipeline_model_parallel_size: 1
  disable_bias_linear: True
  use_flash_attn: True
  use_distributed_optimizer: True
  device_type: iluvatar 
  precision:
    fp16: True
    initial_loss_scale: 522893
    min_loss_scale: 1.0
    attention_softmax_in_fp32: True
    accumulate_allreduce_grads_in_fp32: True
  logging:
    log_interval: 1
    tensorboard_log_interval: 1
    wandb_project: "train-aquila-7B" 
    wandb_exp_name: "train-test-7B" 
  checkpoint:
    save_interval: 2000 

model:
  use_mcore_models: true
  num_layers: 32 
  hidden_size: 4096 
  num_attention_heads: 32 
  seq_length: 2048 
  max_position_embeddings: 2048
  norm_epsilon: 1e-5
  use_rotary_position_embeddings: true
  no_position_embedding: true
  swiglu: true
  multiple_of: 256
  normalization: RMSNorm
  rotary_interleaved_patch: true
  untie_embeddings_and_output_weights: true
  init_method_std: 0.02
  attention_dropout: 0.0
  hidden_dropout: 0.0
  weight_decay: 0.1
  clip_grad: 1.0
  train_samples: 100000
  eval_iters: 0
  micro_batch_size: 1
  global_batch_size: 128 
  seed: 1234

  optimizer:
    weight_decay: 0.1
    adam_beta1: 0.9
    adam_beta2: 0.95
    lr_scheduler:
      lr: 2.0e-5
      min_lr: 2.0e-6
      lr_warmup_samples: 500
      lr_decay_style: cosine 

data:
  data_path: ./llama_00_text_document/
  split: 1
  tokenizer:
    tokenizer_type: AquilaTokenizer
    vocab_file: ./examples/aquila/tokenizer/vocab.json
    merge_file: ./examples/aquila/tokenizer/merges.txt
    special_tokens_file: ./examples/aquila/tokenizer/special_tokens.txt
    vocab_size: 100008
