defaults:
  - train: 3b
  - _self_

experiment:
  exp_name: rwkv
  exp_dir: ./outputs
  task:
    type: train
    backend: megatron
    entrypoint: ./flagscale/train/train_rwkv.py
  # cmds:
  #   before_start: source /root/miniconda3/bin/activate flagscale
  runner:
    backend: torchrun
    nnodes: 1
    nproc_per_node: 1
  envs:
    CUDA_VISIBLE_DEVICES: 0
    CUDA_DEVICE_MAX_CONNECTIONS: 1

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
