system: {}
  
model:
  batch_size: 4
  training_dtype: float32
  overwrite: true
  exp_name: Robotics-3.3B
  assets_base_dir: /share/project/hcr/repos/flag-scale/assets
  
data:
  # config_name: robotics_libero
  config_name: test_single_data