system: {}
  
model:
  batch_size: 4
  training_dtype: float32
  ckpt_overwrite: true
  exp_name: Robotics-3.3B
  assets_base_dir: local/assets/dir
  
data:
  # config_name: robotics_libero
  config_name: test_single_data