defaults:
  - train: train_llama2_7b 
  - _self_

experiment:
  exp_name: unified-runner 
  exp_dir: ./outputs_llama2
  entrypoint: ./flagscale/train/train_llama2.py 
  task: train
  hostfile: ./hostfile
  backend: megatron
  shell_cmds: null 
  ssh_port: null
  envs:
    CUDA_VISIBLE_DEVICES: "0,1,2,3,4,5,6,7"
    CUDA_DEVICE_MAX_CONNECTIONS: 1

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra 