##############################################################################
# ================== Stage: Base with CUDA and Dependencies ==================
##############################################################################
ARG CUDA_VERSION=12.8.1

FROM nvcr.io/nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04 AS base 

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=Asia/Shanghai

##############################################################################
# Temporary Installation Directory
##############################################################################
ENV STAGE_DIR=/tmp
RUN mkdir -p ${STAGE_DIR}
ENV WORK_DIR=/workspace
RUN mkdir -p ${WORK_DIR}

##############################################################################
# Install Basic Utilities
##############################################################################
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils && \
    echo "N" | apt-get install -y --no-install-recommends pkg-config && \
    apt-get install -y --no-install-recommends \
        autotools-dev \
        build-essential \
        ca-certificates ccache cmake curl \
        emacs \
        gcc git git-lfs g++ \
        htop \
        iftop iotop \
        libcairo2-dev libfontconfig-dev libibverbs1 libibverbs-dev libnuma-dev libx11-dev lsb-release \
        net-tools nfs-common ninja-build \
        openssh-server openssh-client \
        pdsh psmisc \
        rsync \
        screen software-properties-common sudo \
        tmux tzdata \
        unzip \
        vim \
        wget

##############################################################################
# ==================== Final Stage: Minimal Runtime Image ====================
##############################################################################
FROM nvcr.io/nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04 AS final

ARG WORK_DIR=/workspace
ARG STAGE_DIR=/tmp
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND noninteractive

##############################################################################
# Temporary Installation Directory
##############################################################################
RUN mkdir -p ${WORK_DIR} && \
    mkdir -p ${STAGE_DIR}

##############################################################################
# Install Basic Utilities
##############################################################################
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils && \
    echo "N" | apt-get install -y --no-install-recommends pkg-config && \
    apt-get install -y --no-install-recommends \
        autotools-dev \
        build-essential \
        ca-certificates ccache cmake curl \
        emacs \
        gcc git git-lfs g++ \
        htop \
        iftop iotop \
        libcairo2-dev libfontconfig-dev libibverbs1 libibverbs-dev libnuma-dev libx11-dev lsb-release \
        net-tools nfs-common ninja-build \
        openssh-server openssh-client \
        pdsh psmisc \
        rsync \
        screen software-properties-common sudo \
        tmux tzdata \
        unzip \
        vim \
        wget

##############################################################################
# Clear
##############################################################################
RUN apt-get clean && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf ${STAGE_DIR}/*

##############################################################################
# Copy necessary files from build stages
##############################################################################
COPY --from=base /usr/bin/python3.12-config /usr/bin/python3.12-config
COPY --from=base /usr/bin/python3 /usr/bin/python3

RUN ln -sf /usr/bin/python3.12-config /usr/bin/python3-config && \
    ln -s /usr/bin/python3 /usr/bin/python
