FROM cr.metax-tech.com/public-ai-release/maca/modelzoo.llm.vllm:maca.ai2.33.0.13-torch2.6-py310-ubuntu22.04-amd64

##############################################################################
# Temporary Installation Directory
##############################################################################
WORKDIR /workspace

##############################################################################
# Install Basic Utilities
##############################################################################
RUN apt-get update && \
    apt-get install -y --no-install-recommends git vim curl wget && \
    rm -rf /var/lib/apt/lists/*

##############################################################################
# cmake >= 4.03
##############################################################################
RUN /opt/conda/bin/pip3 install cryptography gitpython cmake

##############################################################################
# used to generate cmakecache files
# install tooklit Only, IGNORE driver or samples
##############################################################################
RUN wget https://developer.download.nvidia.com/compute/cuda/11.6.0/local_installers/cuda_11.6.0_510.39.01_linux.run && \
    sh cuda_11.6.0_510.39.01_linux.run --silent --toolkit && \
    rm cuda_11.6.0_510.39.01_linux.run

##############################################################################
# Clone FlagScale
##############################################################################
ARG FLAGSCALE_REPO
ARG FLAGSCALE_BRANCH
ARG FLAGSCALE_COMMIT
RUN cd /workspace && \
    git clone -b ${FLAGSCALE_BRANCH} ${FLAGSCALE_REPO} || \
    { echo "Error: Failed to clone the repository or the branch IMAGE_250515 does not exist."; exit 1; } && \
    cd FlagScale && \
    git checkout ${FLAGSCALE_COMMIT} || \
    { echo "Error: Failed to checkout commit ${FLAGSCALE_COMMIT}. Please ensure the commit ID is correct and exists in the repository."; exit 1; } && \
    chmod +x install/install-requirements-metax.sh

##############################################################################
# Install flagscale-inference requirements
##############################################################################
RUN cd /workspace/FlagScale && \
    ./install/install-requirements-metax.sh --env inference

##############################################################################
# Ensure that no matter what bash enters interactive mode
# it can enter the same environment
##############################################################################
RUN echo "conda activate base" >> ~/.bashrc

##############################################################################
# Clear
##############################################################################
RUN apt-get clean && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf /root/.cache/* && \
        rm -rf /workspace/FlagScale
