system:
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  context_parallel_size: 1
  wandb_enabled: true
  seed: 42
  project_name: ${experiment.exp_name}
  exp_name: ${experiment.exp_name}
  batch_size: 1
  train_steps: 100
  log_freq: 10
  output_directory: ${experiment.exp_dir}/ckpt
  
model:
  # change to your model path
  checkpoint_dir: /models/lerobot/pi0 
  resume: false
  ckpt_overwrite: true
  # change to your stat_path (lerobot format)
  stat_path: /models/lerobot/aloha_mobile_cabinet/meta/stats.json
  action_horizon: 14
  action_steps: 30

data:
  # change to your tokenizer path
  tokenizer_path: /models/google/paligemma-3b-pt-224
  # change to your data path
  data_path: /repos/flagscale_dataset/flag-scale/demo_0913_n2/wds-1
  state_key: eepose
  action_key: eepose
  action_token_key: action_eepose_token
  vision_root: ""