system:
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 1
  expert_model_parallel_size: 1
  context_parallel_size: 2
  ulysses_sequence_parallel_size: 2
  sequence_parallel: true
  use_distributed_optimizer: false
  # overlap_grad_reduce: true
  # overlap_param_gather: true
  precision:
    bf16: true
    accumulate_allreduce_grads_in_fp32: False
  logging:
    log_interval: 1
    tensorboard_log_interval: 1
    wandb_project: mistral-7b
    wandb_exp_name: mistral-7b
  checkpoint:
    save_interval: 10000


model:
  use_mcore_models: true
  transformer_impl: transformer_engine
  num_layers: 32
  hidden_size: 4096
  ffn_hidden_size: 14336
  num_attention_heads: 32
  seq_length: 32768
  max_position_embeddings: 32768
  swiglu: true
  normalization: RMSNorm
  norm_epsilon: 1e-05
  group_query_attention: true
  num_query_groups: 8
  init_method_std: 0.02
  attention_dropout: 0.0
  hidden_dropout: 0.0
  disable_bias_linear: true
  add_qkv_bias: false
  position_embedding_type: rope
  rotary_base: 1000000.0
  no_masked_softmax_fusion: true
  untie_embeddings_and_output_weights: true

  seed: 42
  train_iters: 100
  micro_batch_size: 1
  global_batch_size: 8
  clip_grad: 1.0
  eval_interval: 100
  eval_iters: 10

  optimizer:
    lr: 1e-4
    weight_decay: 0.1
    lr_scheduler:
      min_lr: 1.0e-5
      lr_warmup_iters: 50
      lr_decay_iters: 100
      lr_decay_style: cosine


data:
  data_path: xxx
  split: 1
  tokenizer:
    tokenizer_type: QwenTokenizer
    tokenizer_path: xxx
    vocab_file: examples/aquila/tokenizer/vocab.json
    merge_file: examples/aquila/tokenizer/merges.txt
    special_tokens_file: examples/aquila/tokenizer/special_tokens.txt
    vocab_size: 151851
    make_vocab_size_divisible_by: 64
