engine:
  model: /models/lerobot/pi0
  tokenizer: /models/google/paligemma-3b-pt-224
  stat_path: /models/lerobot/aloha_mobile_cabinet/meta/stats.json
  loader: pi0
  results_path: ${experiment.exp_dir}/results
  device: "cuda"
  output_format: image
  torch_dtype: bf16
  transformations:
    LogIOTransformation:
      log_level: "info"
    StateScopeTransformation:
      {}

generate:
  images_keys:
    - observation.images.camera0
    - observation.images.camera1
    - observation.images.camera2
  images_shape: [3, 480, 640]
  batch_size: 1
  action_dim: 14
  action_horizon: 10
  state_key: observation.state
  instruction:
    task: 
      - "retro serie of different cars with different colors and shapes, mdjrny-v4 style"

