export GLOO_SOCKET_IFNAME=enp67s0f5
export TP_SOCKET_IFNAME=enp67s0f5
export RAY_EXPERIMENTAL_NOSET_ASCEND_RT_VISIBLE_DEVICES=1
export ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

export MM_ALL_REDUCE_OP_THRESHOLD=1000000
export HCCL_OP_EXPANSION_MODE="AIV"
export NUMEXPR_MAX_THREADS=192
export OMNI_PLANNER_CONFIG="/home/omni/omni_planner/config.yaml"
# unset OMNI_PLANNER_CONFIG


export ENABLE_MOE_EP=1
export ENABLE_ALLTOALL=1
export DP_SIZE=4
unset VLLM_ENABLE_PROFILING
unset VLLM_TORCH_PROFILER_DIR

ray start --address='7.242.104.183:6377' --num-gpus=8
