system:
  distributed_backend: nccl
  reset_position_ids: False
  reset_attention_mask: False
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  use_distributed_optimizer: True
  precision:
    fp16: False
    bf16: True
  logging:
    log_interval: 10
    tensorboard_log_interval: 10
    tensorboard_dir: ./outputs/logs
  checkpoint:
    save: ./outputs/ckpts/
    save_interval: 1000

model:
  num_layers: 32
  hidden_size: 2560
  num_attention_heads: 8
  seq_length: 4096
  max_position_embeddings: 4096
  init_method_std: 0.02
  clip_grad: 1.0
  micro_batch_size: 1
  global_batch_size: 1
  train_iters: 2000
  eval_iters: 2
  eval_interval: 1000
  seed: 1234
  ckpt_format: torch
  optimizer:
    weight_decay: 0.01
    adam_beta1: 0.9
    adam_beta2: 0.99
    lr_scheduler:
      lr: 6.0e-4
      min_lr: 6.0e-5
      lr_warmup_fraction: 0.01
      lr_decay_style: cosine

data:
  data_path: ${data_path:??}
  split: "1"
  tokenizer:
    tokenizer_path: ${tokenizer_path:??} # The vocab file can be found at https://github.com/RWKV-Vibe/RWKV-LM-V7/tree/main/data/tokenizer
