system:
  output_dir: /share/project/hcr/models/train/lerobot/pi0
  resume: false
  seed: 42
  num_workers: 4
  batch_size: 8
  steps: 10000
  eval_freq: 2000
  log_freq: 100
  save_checkpoint: "true"
  save_freq: 2000
  use_policy_training_preset: "true"
  # optimizer.type choices: adam, adamw, sgd, multi_adam
  optimizer.type: adamw
  optimizer.lr: 1e-3
  optimizer.weight_decay: 1e-2
  optimizer.grad_clip_norm: 10
  optimizer.eps: 1e-8
  wandb.mode: offline
model:
  policy.type: pi0
  # TODO: Update model_path to your local model path
  policy.repo_id: /path/to/your/models/lerobot/pi0
  policy.n_obs_steps: 1
  policy.device: cuda
  policy.use_amp: "false"
  policy.push_to_hub: "false"
  
data:
  dataset.repo_id: danaaubakirova/koch_test
  dataset.video_backend: pyav
