diff --git a/docker/Dockerfile.metax b/docker/Dockerfile.metax
new file mode 100644
index 00000000..97985466
--- /dev/null
+++ b/docker/Dockerfile.metax
@@ -0,0 +1,64 @@
+ARG MACA_VERSION=ai3.0.0.5
+ARG TORCH_VERSION=2.6
+ARG PYTHON_VERSION=310
+FROM cr.metax-tech.com/public-ai-release/maca/modelzoo.llm.vllm:maca.${MACA_VERSION}-torch${TORCH_VERSION}-py${PYTHON_VERSION}-ubuntu22.04-amd64
+
+##############################################################################
+# Temporary Installation Directory
+##############################################################################
+WORKDIR /workspace
+
+##############################################################################
+# Install Basic Utilities
+##############################################################################
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends git vim curl wget && \
+    rm -rf /var/lib/apt/lists/*
+
+##############################################################################
+# cmake >= 4.03
+##############################################################################
+RUN /opt/conda/bin/pip3 install cryptography gitpython cmake
+
+##############################################################################
+# used to generate cmakecache files
+# install tooklit Only, IGNORE driver or samples
+##############################################################################
+ARG CUDA_VERSION=11.6.0
+ARG TOOLKIT_VERSION=11.6.0_510.39.01
+RUN wget https://developer.download.nvidia.com/compute/cuda/${CUDA_VERSION}/local_installers/cuda_${TOOLKIT_VERSION}_linux.run && \
+    sh cuda_${TOOLKIT_VERSION}_linux.run --silent --toolkit && \
+    rm cuda_${TOOLKIT_VERSION}_linux.run
+
+##############################################################################
+# Clone FlagScale
+##############################################################################
+ARG FLAGSCALE_REPO
+ARG FLAGSCALE_BRANCH
+ARG FLAGSCALE_COMMIT
+RUN cd /workspace && \
+    git clone -b ${FLAGSCALE_BRANCH} ${FLAGSCALE_REPO} || \
+    { echo "Error: Failed to clone the repository or the branch IMAGE_250515 does not exist."; exit 1; } && \
+    cd FlagScale && \
+    git checkout ${FLAGSCALE_COMMIT} || \
+    { echo "Error: Failed to checkout commit ${FLAGSCALE_COMMIT}. Please ensure the commit ID is correct and exists in the repository."; exit 1; }
+
+##############################################################################
+# Install flagscale-inference requirements
+##############################################################################
+RUN cd /workspace/FlagScale && \
+    ./install/install-requirements-metax.sh --env inference
+
+##############################################################################
+# Ensure that no matter what bash enters interactive mode
+# it can enter the same environment
+##############################################################################
+RUN echo "conda activate base" >> ~/.bashrc
+
+##############################################################################
+# Clear
+##############################################################################
+RUN apt-get clean && \
+        rm -rf /var/lib/apt/lists/* && \
+        rm -rf /root/.cache/* && \
+        rm -rf /workspace/FlagScale

