# Patterns: Path to the pattern file specifying expert deployment configuration.

#     The placement pattern is represented as a three-dimensional binary matrix (`expert_mapping`) indicating
#     the presence (`1`) or absence (`0`) of experts (EPs) across dimensions of devices, layers, and expert IDs (`epid`).
#     Specifically, the three dimensions are:

#         - deviceid: Identifier of the device.
#         - layerid: Identifier of the MoE layer.
#         - epid: Identifier of the expert within a layer.
#                 Note that experts in different layers may share the same `epid`, but they represent distinct experts.

#     Thus, `expert_mapping[deviceid][layerid][epid] = 1` indicates that the expert identified by `epid` at layer `layerid`
#     is deployed on device `deviceid`. Conversely, a value of `0` indicates the absence of that expert on the specified device and layer.

#     Note: The same `epid` within the same `layerid` can have multiple entries with the value `1` across different devices.
#     This means the combination `(layerid, epid)` alone does not uniquely identify a deployment;
#     rather, experts may be replicated across multiple devices to enable parallelism or redundancy.

#     Defaults to None.
pattern_path: "../patterns/base_patterns/DSV3_baseline_16_devices_58_MoE_Layers.npy"

#define max_layer_num as a constant 58 (for deepseek moe layer num 58)
max_moe_layer_num: 58
max_batch_size: 256
max_top_k: 8

# enable_dump: True
# dump_dir: "/home/profiling/dump_data"

# Optimizers
Optimizers:
  - expert_balance_optimizer.ExpertsBalanceOptimizer:
      batch_size: 48
      top_k_count: 8
  - heat_optimizer.HEAT_ExpertsBalancer:
      is_global_maximum_offset: True
  - resdispatch_optimizer.ResDis_ExpertsBalancer:
      is_rand_op: False