defaults:
  - train: train_aquila_7b 
  - _self_

experiment:
  exp_name: aquila2
  exp_dir: ./outputs
  task:
    type: train
    backend: megatron
    entrypoint: /home/FlagScale/flagscale/train/train_aquila.py
  runner:
    backend: torchrun
    nnodes: 1 
    nproc_per_node: 8 
  envs:
    PYTORCH_SKIP_COMPILE_CHECK: 1
    MACA_PATH: /opt/maca
    MACA_SMALL_PAGESIZE_ENABLE: 1
    PYTORCH_ENABLE_SAME_RANK_A100: 1
    CUCC_PATH: /opt/maca/tools/cu-bridge
    CUDA_PATH: /opt/maca/tools/cu-bridge
    SET_DEVICE_NUMA_PREFERRED: 1
    MHA_USE_BLAS: ON
    MHA_BWD_NO_ATOMIC_F64: 1
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra 
