defaults:
  - train: mixtral_8x7b 
  - _self_

experiment:
  exp_name: unified-runner 
  exp_dir: ./outputs
  entrypoint: ./flagscale/train/train_mixtral.py 
  task: train
  hostfile: <xx>
  backend: megatron
  shell_cmds: null 
  ssh_port: null
  envs:
    MACA_PATH: /opt/maca
    MACA_SMALL_PAGESIZE_ENABLE: 1
    PYTORCH_ENABLE_SAME_RANK_A100: 1
    CUCC_PATH: /opt/maca/tools/cu-bridge
    CUDA_PATH: /opt/maca/tools/cu-bridge
    SET_DEVICE_NUMA_PREFERRED: 1
    MHA_USE_BLAS: ON
    MHA_BWD_NO_ATOMIC_F64: 1
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra 
