defaults:
  - _self_
  - serve: serve_qwen2.5_multiple_models

experiment:
  exp_name: serve_qwen2.5_multiple_models
  exp_dir: outputs/${experiment.exp_name}
  task:
    type: serve
    backend: vllm
    entrypoint: ./flagscale/serve/serve_multiple_qwens.py
  runner:
    hostfile: null
  envs:
    CUDA_VISIBLE_DEVICES: 0
    CUDA_DEVICE_MAX_CONNECTIONS: 1

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
