name: Auto Labeler

on:
  push:
    branches: [ "main" ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Labeler Action
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ./.github/labeler-config.yml
